from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProjectViewSet, TaskViewSet

# Create a router
router = DefaultRouter()

# Register viewsets
router.register(r'projects', ProjectViewSet, basename='project')
router.register(r'tasks', TaskViewSet, basename='task')

# Define URL patterns
urlpatterns = [
    # Include router-generated URLs
    path('', include(router.urls)),
    
    # Add nested routes manually (these can't be generated by the router)
    path('projects/<int:project_pk>/tasks/', 
         TaskViewSet.as_view({'get': 'list', 'post': 'create'}), 
         name='project-task-list'),
    path('projects/<int:project_pk>/tasks/<int:pk>/', 
         TaskViewSet.as_view({
             'get': 'retrieve',
             'put': 'update',
             'patch': 'partial_update',
             'delete': 'destroy'
         }), 
         name='project-task-detail'),
]
